# Make sure to check the documentation at https://goreleaser.com
project_name: communicator
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
      - leslieleung/{{ .ProjectName }}:{{ .Tag }}
      - leslieleung/{{ .ProjectName }}:latest
    extra_files:
      - .
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
